M48
; DRILL file {KiCad 8.0.5} date 2025-01-07T17:40:30+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-01-07T17:40:30+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X4.8031Y-2.5543
X4.8031Y-4.9559
X6.6457Y-2.5543
X6.6457Y-4.9559
M30
